spring:
  application:
    name: SHRAPNEL-CORE
  security:
    user:
      name: naren
      password: 123

  datasource:
    url: jdbc:postgresql://localhost:5432/shrapnel_db
    username: postgres
    password: Jan10@2013
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        envers:
          audit_table_suffix: _AUDIT_LOG
          revision_field_name: rev_id

  servlet:
    multipart:
      max-file-size: 10GB
      max-request-size: 10GB
      file-size-threshold: 2KB
      location: ./shrapnel_data/staging

  threads:
    virtual:
      enabled: true

  server:
    connection-timeout: 300000
# Root Level: Configuration for the Shatter Engine
shrapnel:
  engine:
    storage-path: ./shrapnel_data
    shard-size-mb: 1
  blockchain:
    provider-url: https://polygon-amoy.g.alchemy.com/v2/i66R6pp3uYEGBClog1chm
    private-key: ${BLOCKCHAIN_PRIVATE_KEY:}
    default-gas-price: 50000000000    # fallback in wei
    default-gas-limit: 50000

mlflow:
  tracking-uri: ${MLFLOW_TRACKING_URI:http://localhost:5000}
  experiment-name: shrapnel-blockchain
